/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActualiteRouteImport } from './routes/actualite'
import { Route as MethodologieRouteImport } from './routes/methodologie'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as BilansIndexRouteImport } from './routes/bilans/index'
import { Route as BilansPresidentRouteImport } from './routes/bilans/$president'
import { Route as DeputesUidRouteImport } from './routes/deputes/$uid'
import { Route as GroupesUidRouteImport } from './routes/groupes/$uid'
import { Route as LoisIndexRouteImport } from './routes/lois/index'
import { Route as LoisUidRouteImport } from './routes/lois/$uid'
import { Route as ProgrammesIndexRouteImport } from './routes/programmes/index'
import { Route as ProgrammesComparerRouteImport } from './routes/programmes/comparer'
import { Route as ProgrammesQuizRouteImport } from './routes/programmes/quiz'
import { Route as ProgrammesVotesRouteImport } from './routes/programmes/votes'
import { Route as ThemesIndexRouteImport } from './routes/themes/index'
import { Route as ThemesSlugRouteImport } from './routes/themes/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualiteRoute = ActualiteRouteImport.update({
  id: '/actualite',
  path: '/actualite',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologieRoute = MethodologieRouteImport.update({
  id: '/methodologie',
  path: '/methodologie',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const BilansIndexRoute = BilansIndexRouteImport.update({
  id: '/bilans/',
  path: '/bilans/',
  getParentRoute: () => rootRouteImport,
} as any)
const BilansPresidentRoute = BilansPresidentRouteImport.update({
  id: '/bilans/$president',
  path: '/bilans/$president',
  getParentRoute: () => rootRouteImport,
} as any)
const DeputesUidRoute = DeputesUidRouteImport.update({
  id: '/deputes/$uid',
  path: '/deputes/$uid',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupesUidRoute = GroupesUidRouteImport.update({
  id: '/groupes/$uid',
  path: '/groupes/$uid',
  getParentRoute: () => rootRouteImport,
} as any)
const LoisIndexRoute = LoisIndexRouteImport.update({
  id: '/lois/',
  path: '/lois/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoisUidRoute = LoisUidRouteImport.update({
  id: '/lois/$uid',
  path: '/lois/$uid',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesIndexRoute = ProgrammesIndexRouteImport.update({
  id: '/programmes/',
  path: '/programmes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesComparerRoute = ProgrammesComparerRouteImport.update({
  id: '/programmes/comparer',
  path: '/programmes/comparer',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesQuizRoute = ProgrammesQuizRouteImport.update({
  id: '/programmes/quiz',
  path: '/programmes/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesVotesRoute = ProgrammesVotesRouteImport.update({
  id: '/programmes/votes',
  path: '/programmes/votes',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesIndexRoute = ThemesIndexRouteImport.update({
  id: '/themes/',
  path: '/themes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesSlugRoute = ThemesSlugRouteImport.update({
  id: '/themes/$slug',
  path: '/themes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actualite': typeof ActualiteRoute
  '/methodologie': typeof MethodologieRoute
  '/quiz': typeof QuizRoute
  '/recherche': typeof RechercheRoute
  '/bilans/$president': typeof BilansPresidentRoute
  '/deputes/$uid': typeof DeputesUidRoute
  '/groupes/$uid': typeof GroupesUidRoute
  '/lois/$uid': typeof LoisUidRoute
  '/programmes/comparer': typeof ProgrammesComparerRoute
  '/programmes/quiz': typeof ProgrammesQuizRoute
  '/programmes/votes': typeof ProgrammesVotesRoute
  '/themes/$slug': typeof ThemesSlugRoute
  '/bilans/': typeof BilansIndexRoute
  '/lois/': typeof LoisIndexRoute
  '/programmes/': typeof ProgrammesIndexRoute
  '/themes/': typeof ThemesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actualite': typeof ActualiteRoute
  '/methodologie': typeof MethodologieRoute
  '/quiz': typeof QuizRoute
  '/recherche': typeof RechercheRoute
  '/bilans/$president': typeof BilansPresidentRoute
  '/deputes/$uid': typeof DeputesUidRoute
  '/groupes/$uid': typeof GroupesUidRoute
  '/lois/$uid': typeof LoisUidRoute
  '/programmes/comparer': typeof ProgrammesComparerRoute
  '/programmes/quiz': typeof ProgrammesQuizRoute
  '/programmes/votes': typeof ProgrammesVotesRoute
  '/themes/$slug': typeof ThemesSlugRoute
  '/bilans': typeof BilansIndexRoute
  '/lois': typeof LoisIndexRoute
  '/programmes': typeof ProgrammesIndexRoute
  '/themes': typeof ThemesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actualite': typeof ActualiteRoute
  '/methodologie': typeof MethodologieRoute
  '/quiz': typeof QuizRoute
  '/recherche': typeof RechercheRoute
  '/bilans/$president': typeof BilansPresidentRoute
  '/deputes/$uid': typeof DeputesUidRoute
  '/groupes/$uid': typeof GroupesUidRoute
  '/lois/$uid': typeof LoisUidRoute
  '/programmes/comparer': typeof ProgrammesComparerRoute
  '/programmes/quiz': typeof ProgrammesQuizRoute
  '/programmes/votes': typeof ProgrammesVotesRoute
  '/themes/$slug': typeof ThemesSlugRoute
  '/bilans/': typeof BilansIndexRoute
  '/lois/': typeof LoisIndexRoute
  '/programmes/': typeof ProgrammesIndexRoute
  '/themes/': typeof ThemesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actualite'
    | '/methodologie'
    | '/quiz'
    | '/recherche'
    | '/bilans/$president'
    | '/deputes/$uid'
    | '/groupes/$uid'
    | '/lois/$uid'
    | '/programmes/comparer'
    | '/programmes/quiz'
    | '/programmes/votes'
    | '/themes/$slug'
    | '/bilans/'
    | '/lois/'
    | '/programmes/'
    | '/themes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actualite'
    | '/methodologie'
    | '/quiz'
    | '/recherche'
    | '/bilans/$president'
    | '/deputes/$uid'
    | '/groupes/$uid'
    | '/lois/$uid'
    | '/programmes/comparer'
    | '/programmes/quiz'
    | '/programmes/votes'
    | '/themes/$slug'
    | '/bilans'
    | '/lois'
    | '/programmes'
    | '/themes'
  id:
    | '__root__'
    | '/'
    | '/actualite'
    | '/methodologie'
    | '/quiz'
    | '/recherche'
    | '/bilans/$president'
    | '/deputes/$uid'
    | '/groupes/$uid'
    | '/lois/$uid'
    | '/programmes/comparer'
    | '/programmes/quiz'
    | '/programmes/votes'
    | '/themes/$slug'
    | '/bilans/'
    | '/lois/'
    | '/programmes/'
    | '/themes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActualiteRoute: typeof ActualiteRoute
  MethodologieRoute: typeof MethodologieRoute
  QuizRoute: typeof QuizRoute
  RechercheRoute: typeof RechercheRoute
  BilansPresidentRoute: typeof BilansPresidentRoute
  DeputesUidRoute: typeof DeputesUidRoute
  GroupesUidRoute: typeof GroupesUidRoute
  LoisUidRoute: typeof LoisUidRoute
  ProgrammesComparerRoute: typeof ProgrammesComparerRoute
  ProgrammesQuizRoute: typeof ProgrammesQuizRoute
  ProgrammesVotesRoute: typeof ProgrammesVotesRoute
  ThemesSlugRoute: typeof ThemesSlugRoute
  BilansIndexRoute: typeof BilansIndexRoute
  LoisIndexRoute: typeof LoisIndexRoute
  ProgrammesIndexRoute: typeof ProgrammesIndexRoute
  ThemesIndexRoute: typeof ThemesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualite': {
      id: '/actualite'
      path: '/actualite'
      fullPath: '/actualite'
      preLoaderRoute: typeof ActualiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodologie': {
      id: '/methodologie'
      path: '/methodologie'
      fullPath: '/methodologie'
      preLoaderRoute: typeof MethodologieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bilans/': {
      id: '/bilans/'
      path: '/bilans'
      fullPath: '/bilans/'
      preLoaderRoute: typeof BilansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bilans/$president': {
      id: '/bilans/$president'
      path: '/bilans/$president'
      fullPath: '/bilans/$president'
      preLoaderRoute: typeof BilansPresidentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deputes/$uid': {
      id: '/deputes/$uid'
      path: '/deputes/$uid'
      fullPath: '/deputes/$uid'
      preLoaderRoute: typeof DeputesUidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groupes/$uid': {
      id: '/groupes/$uid'
      path: '/groupes/$uid'
      fullPath: '/groupes/$uid'
      preLoaderRoute: typeof GroupesUidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lois/': {
      id: '/lois/'
      path: '/lois'
      fullPath: '/lois/'
      preLoaderRoute: typeof LoisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lois/$uid': {
      id: '/lois/$uid'
      path: '/lois/$uid'
      fullPath: '/lois/$uid'
      preLoaderRoute: typeof LoisUidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/': {
      id: '/programmes/'
      path: '/programmes'
      fullPath: '/programmes/'
      preLoaderRoute: typeof ProgrammesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/comparer': {
      id: '/programmes/comparer'
      path: '/programmes/comparer'
      fullPath: '/programmes/comparer'
      preLoaderRoute: typeof ProgrammesComparerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/quiz': {
      id: '/programmes/quiz'
      path: '/programmes/quiz'
      fullPath: '/programmes/quiz'
      preLoaderRoute: typeof ProgrammesQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/votes': {
      id: '/programmes/votes'
      path: '/programmes/votes'
      fullPath: '/programmes/votes'
      preLoaderRoute: typeof ProgrammesVotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes/': {
      id: '/themes/'
      path: '/themes'
      fullPath: '/themes/'
      preLoaderRoute: typeof ThemesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes/$slug': {
      id: '/themes/$slug'
      path: '/themes/$slug'
      fullPath: '/themes/$slug'
      preLoaderRoute: typeof ThemesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActualiteRoute: ActualiteRoute,
  MethodologieRoute: MethodologieRoute,
  QuizRoute: QuizRoute,
  RechercheRoute: RechercheRoute,
  BilansPresidentRoute: BilansPresidentRoute,
  DeputesUidRoute: DeputesUidRoute,
  GroupesUidRoute: GroupesUidRoute,
  LoisUidRoute: LoisUidRoute,
  ProgrammesComparerRoute: ProgrammesComparerRoute,
  ProgrammesQuizRoute: ProgrammesQuizRoute,
  ProgrammesVotesRoute: ProgrammesVotesRoute,
  ThemesSlugRoute: ThemesSlugRoute,
  BilansIndexRoute: BilansIndexRoute,
  LoisIndexRoute: LoisIndexRoute,
  ProgrammesIndexRoute: ProgrammesIndexRoute,
  ThemesIndexRoute: ThemesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
