/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as LoisUidRouteImport } from './routes/lois/$uid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const LoisUidRoute = LoisUidRouteImport.update({
  id: '/lois/$uid',
  path: '/lois/$uid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recherche': typeof RechercheRoute
  '/lois/$uid': typeof LoisUidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recherche': typeof RechercheRoute
  '/lois/$uid': typeof LoisUidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/recherche': typeof RechercheRoute
  '/lois/$uid': typeof LoisUidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/recherche' | '/lois/$uid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/recherche' | '/lois/$uid'
  id: '__root__' | '/' | '/recherche' | '/lois/$uid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RechercheRoute: typeof RechercheRoute
  LoisUidRoute: typeof LoisUidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lois/$uid': {
      id: '/lois/$uid'
      path: '/lois/$uid'
      fullPath: '/lois/$uid'
      preLoaderRoute: typeof LoisUidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RechercheRoute: RechercheRoute,
  LoisUidRoute: LoisUidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
