/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MethodologieRouteImport } from './routes/methodologie'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as DeputesUidRouteImport } from './routes/deputes/$uid'
import { Route as GroupesUidRouteImport } from './routes/groupes/$uid'
import { Route as LoisUidRouteImport } from './routes/lois/$uid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologieRoute = MethodologieRouteImport.update({
  id: '/methodologie',
  path: '/methodologie',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const DeputesUidRoute = DeputesUidRouteImport.update({
  id: '/deputes/$uid',
  path: '/deputes/$uid',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupesUidRoute = GroupesUidRouteImport.update({
  id: '/groupes/$uid',
  path: '/groupes/$uid',
  getParentRoute: () => rootRouteImport,
} as any)
const LoisUidRoute = LoisUidRouteImport.update({
  id: '/lois/$uid',
  path: '/lois/$uid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/methodologie': typeof MethodologieRoute
  '/quiz': typeof QuizRoute
  '/recherche': typeof RechercheRoute
  '/deputes/$uid': typeof DeputesUidRoute
  '/groupes/$uid': typeof GroupesUidRoute
  '/lois/$uid': typeof LoisUidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/methodologie': typeof MethodologieRoute
  '/quiz': typeof QuizRoute
  '/recherche': typeof RechercheRoute
  '/deputes/$uid': typeof DeputesUidRoute
  '/groupes/$uid': typeof GroupesUidRoute
  '/lois/$uid': typeof LoisUidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/methodologie': typeof MethodologieRoute
  '/quiz': typeof QuizRoute
  '/recherche': typeof RechercheRoute
  '/deputes/$uid': typeof DeputesUidRoute
  '/groupes/$uid': typeof GroupesUidRoute
  '/lois/$uid': typeof LoisUidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/methodologie'
    | '/quiz'
    | '/recherche'
    | '/deputes/$uid'
    | '/groupes/$uid'
    | '/lois/$uid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/methodologie'
    | '/quiz'
    | '/recherche'
    | '/deputes/$uid'
    | '/groupes/$uid'
    | '/lois/$uid'
  id:
    | '__root__'
    | '/'
    | '/methodologie'
    | '/quiz'
    | '/recherche'
    | '/deputes/$uid'
    | '/groupes/$uid'
    | '/lois/$uid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MethodologieRoute: typeof MethodologieRoute
  QuizRoute: typeof QuizRoute
  RechercheRoute: typeof RechercheRoute
  DeputesUidRoute: typeof DeputesUidRoute
  GroupesUidRoute: typeof GroupesUidRoute
  LoisUidRoute: typeof LoisUidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodologie': {
      id: '/methodologie'
      path: '/methodologie'
      fullPath: '/methodologie'
      preLoaderRoute: typeof MethodologieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deputes/$uid': {
      id: '/deputes/$uid'
      path: '/deputes/$uid'
      fullPath: '/deputes/$uid'
      preLoaderRoute: typeof DeputesUidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groupes/$uid': {
      id: '/groupes/$uid'
      path: '/groupes/$uid'
      fullPath: '/groupes/$uid'
      preLoaderRoute: typeof GroupesUidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lois/$uid': {
      id: '/lois/$uid'
      path: '/lois/$uid'
      fullPath: '/lois/$uid'
      preLoaderRoute: typeof LoisUidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MethodologieRoute: MethodologieRoute,
  QuizRoute: QuizRoute,
  RechercheRoute: RechercheRoute,
  DeputesUidRoute: DeputesUidRoute,
  GroupesUidRoute: GroupesUidRoute,
  LoisUidRoute: LoisUidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
